repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ --filter-files, src/ ]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [ python ]
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [ python ]
        pass_filenames: false
        require_serial: true
