"""Initial tables v3

Revision ID: 141fd9c31b2d
Revises: 19f45dae2caa
Create Date: 2024-05-07 15:09:30.013639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141fd9c31b2d'
down_revision: Union[str, None] = '19f45dae2caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation', 'advertisement_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('moderation_advertisement_id_key', 'moderation', type_='unique')
    op.drop_constraint('moderation_advertisement_id_fkey', 'moderation', type_='foreignkey')
    op.create_foreign_key(None, 'moderation', 'advertisement', ['advertisement_id'], ['oid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderation', type_='foreignkey')
    op.create_foreign_key('moderation_advertisement_id_fkey', 'moderation', 'advertisement', ['advertisement_id'], ['oid'], ondelete='CASCADE')
    op.create_unique_constraint('moderation_advertisement_id_key', 'moderation', ['advertisement_id'])
    op.alter_column('moderation', 'advertisement_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
