"""Initial tables v1

Revision ID: 1e119aeb298f
Revises: 
Create Date: 2024-05-27 14:12:01.045913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e119aeb298f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('oid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_category_code'), 'category', ['code'], unique=True)
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=True)
    op.create_table('user',
    sa.Column('oid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('number_phone', sa.String(length=11), nullable=False),
    sa.Column('time_call', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_number_phone'), 'user', ['number_phone'], unique=True)
    op.create_table('advertisement',
    sa.Column('oid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('number_of_views', sa.Integer(), nullable=False),
    sa.Column('photo', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.oid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('moderation',
    sa.Column('oid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=False),
    sa.Column('advertisement_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.oid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation')
    op.drop_table('advertisement')
    op.drop_index(op.f('ix_user_number_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.drop_index(op.f('ix_category_code'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
